return {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    keys = {
        {
            "<leader>a",
            function()
                require("harpoon"):list():add()
            end,
        },
        {
            "<leader><C-h>",
            function()
                require("harpoon"):list():replace_at(1)
            end,
        },
        {
            "<leader><C-t>",
            function()
                require("harpoon"):list():replace_at(2)
            end,
        },
        {
            "<leader><C-n>",
            function()
                require("harpoon"):list():replace_at(3)
            end,
        },
        {
            "<leader><C-s>",
            function()
                require("harpoon"):list():replace_at(4)
            end,
        },
        {
            "<C-h>",
            function()
                require("harpoon"):list():select(1)
            end,
        },
        {
            "<C-t>",
            function()
                require("harpoon"):list():select(2)
            end,
        },
        {
            "<C-n>",
            function()
                require("harpoon"):list():select(3)
            end,
        },
        {
            "<C-s>",
            function()
                require("harpoon"):list():select(4)
            end,
        },
        {
            "<C-e>",
            function()
                require("harpoon").ui:toggle_quick_menu(require("harpoon"):list())
            end,
        },
        {
            "<C-e>",
            function()
                require("harpoon").ui:toggle_quick_menu(require("harpoon"):list())
            end,
        },
    },
    config = function()
        require("harpoon").setup()
    end,
}
